export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCTS = 'ADD_PRODUCTS'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_LIST = 'UPDATE_LIST'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

export const CHANGE_PAGE = 'CHANGE_PAGE'
